name: Adblock DAT File Generator

on:
  schedule:
    # 每天1点，9点，17点执行
    - cron: '0 1,9,17 * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  generate-and-upload:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Download CN list
        run: |
          curl -L "https://raw.githubusercontent.com/217heidai/adblockfilters/main/rules/adblockdomainlite.txt" -o cn.txt
          
      - name: Download Global list
        run: |
          curl -L "https://raw.githubusercontent.com/217heidai/adblockfilters/main/rules/adblockdomain.txt" -o global.txt

      - name: Remove lines starting with !
        run: |
          grep -v '^!' cn.txt > cn_filtered.txt && mv cn_filtered.txt cn.txt
          grep -v '^!' global.txt > global_filtered.txt && mv global_filtered.txt global.txt

      - name: Remove duplicates from global list
        run: |
          # 获取cn.txt中的域名列表
          comm -12 <(sort cn.txt) <(sort global.txt) > duplicates.txt
          # 从global.txt中移除重复项
          grep -vxFf duplicates.txt global.txt > global_unique.txt && mv global_unique.txt global.txt

      - name: Create adblock.dat file
        run: |
          node generate_dat.js

      - name: Get current date
        id: date
        run: echo "date=$(date +%Y%m%d-%H%M)" >> $GITHUB_ENV

      - name: Create Release and Upload Asset
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.date }}
          name: adblock.dat ${{ env.date }}
          draft: false
          prerelease: false
          makeLatest: true
          artifacts: ./adblock.dat
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete old releases
        run: |
          # 获取7天前的时间戳
          cutoff_date=$(date -d '7 days ago' +%s)
          
          # 获取所有发布版本
          releases=$(gh release list -R ${{ github.repository }} --limit 100 | awk '{print $1}')
          
          # 遍历并删除7天前的版本
          for release in $releases; do
            # 获取发布日期
            release_date=$(gh release view $release -R ${{ github.repository }} --json createdAt -q .createdAt | cut -d'T' -f1)
            release_timestamp=$(date -d "$release_date" +%s)
            
            # 如果发布日期早于7天前且不是latest标签，则删除
            if [[ $release_timestamp -lt $cutoff_date && "$release" != "latest" ]]; then
              echo "Deleting release: $release"
              gh release delete $release -R ${{ github.repository }} --yes || true
            fi
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}